[package]
name = "falling_leaf"
version = "0.1.0"
edition = "2021"
authors = ["Luca Thomas"]
build = "build.rs"


[dependencies]
stb_image = "*"
nalgebra-glm = "*"
gl = "*"
sdl2 = { version = "*", features = ["bundled", "static-link", "mixer", "image"] }


[build-dependencies]
winresource = "*"
