[package]
name = "falling_leaf"
version = "0.1.0"
edition = "2021"
authors = ["Luca Thomas"]
build = "build.rs"

[lib]
name = "fl_core"
path = "src/core/lib.rs"

[[bin]]
name = "fl_test"
path = "src/main.rs"

[dependencies]
glutin = "*"
glutin-winit = "*"
winit = "*"
raw-window-handle = "*"
stb_image = "*"
nalgebra-glm = "*"
gl = "*"
obj-rs = "*"
fontdue = "*"
fyrox-sound = "*"
fyrox-resource = "*"

[build-dependencies]
winresource = "*"
