[package]
name = "falling_leaf"
version = "0.1.0"
edition = "2021"
authors = ["Luca Thomas"]
build = "build.rs"

[lib]
name = "fl_core"
path = "src/core/lib.rs"

[[bin]]
name = "fl_test"
path = "src/main.rs"

[dependencies]
stb_image = "*"
nalgebra-glm = "*"
gl = "*"
obj-rs = "*"
fontdue = "*"


[dependencies.sdl2]
version = "*"
default-features = false
features = ["image", "mixer", "static-link", "use-vcpkg"]

[package.metadata.vcpkg]
dependencies = ["sdl2", "sdl2-image[libjpeg-turbo,tiff,libwebp]", "sdl2-mixer"]
git = "https://github.com/microsoft/vcpkg"
rev = "2024.06.15"

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md" }


[build-dependencies]
winresource = "*"
