[package]
name = "falling_leaf"
version = "0.1.0"
edition = "2021"
authors = ["Luca Thomas"]
build = "build.rs"


[dependencies]
stb_image = "*"
nalgebra-glm = "*"
russimp = { version = "*", features = ["prebuilt"] }


[build-dependencies]
winresource = "*"
